---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# layers

<!-- badges: start -->
<!-- badges: end -->

The goal of layers is to provide a simple library for doing common reinsurance calculations outside of Analyze Re.

## Installation

You can install the development version of `layers` from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("jfkingiii/layers")
```
## Example

Use the included sample yelt, `yelt_test` to try out some of the `layers` functions.

```{r example}
library(layers)

# Look at the help files
help(package=layers)

# Create some layers and get their metrics
options(scipen = 999)
test_layer <- layer(4000000, 1000000, 1, "yelt_test", lobs=c("PHYSICIANS","CHC","MEDCHOICE"))
gross_layer <- layer(UNLIMITED, 0, 1, "yelt_test", lobs=c("PHYSICIANS","CHC","MEDCHOICE","HOSPITAL"))
test_layer
gross_layer
summary(test_layer)
summary(gross_layer)

# Test some OEPs
VaR(gross_layer, 1 - 1/25, "OEP")
VaR(gross_layer, 1 - 1/100, "OEP")
VaR(test_layer, 1 - 1/100, "OEP")
VaR(test_layer, 1 - 1/100, "OEP")
```

